int is_index_reg (int REGN);
int  is_base_reg (int REGN);
int is_arg_reg (int REGN);
int is_return_val_reg (int REGN);
int non_strict_index_reg (int REGN);
int non_strict_base_reg (int REGN);
int is_caller_saved_reg (int REGN);
int is_callee_saved_reg (int REGN);
int is_general_reg (int REGN);
void spim_asm_internal_label (FILE *stream, const char *prefix, unsigned long labelno);
void spim_asm_globalize_label (FILE *stream, const char *name);
rtx spim_struct_value_rtx (tree fndecl, int incoming);
enum reg_class regno_reg_class (int REGN);
enum reg_class reg_class_from_letter  (char ch);
int IITB_regno_ok_for_base_p  (int REGN);
int regno_ok_for_index_p  (int REGN);
int const_ok_for_letter_p (int VALUE,char CH);
int initial_frame_pointer_offset  (int DEPTH);
 int registers_to_be_saved (void);
int initial_elimination_offset (int from, int to);
rtx function_value  (void);
int constant_address_p  (rtx X);
int legitimate_address1 (enum machine_mode MODE,rtx X);
int legitimate_address2 (enum machine_mode MODE,rtx X);
int  reg_ok_for_base_p1 (rtx x);
int reg_ok_for_base_p2 (rtx x);
int  reg_ok_for_index_p1 (rtx x);
int reg_ok_for_index_p2 (rtx x);
rtx  legitimize_address (rtx X,rtx OLDX, enum machine_mode MODE);
void asm_output_align (FILE *STREAM, int POWER);
void asm_output_skip (FILE  *STREAM,int NBYTES);
void print_operand (FILE *STREAM,rtx X,char CODE);
void print_operand_address (FILE *STREAM,rtx X);
void asm_generate_internal_label (char *STRING,char *PREFIX,int NUM);
void asm_output_local (FILE *STREAM,char *NAME,int SIZE,int ROUNDED);
void asm_output_common (FILE *STREAM,char *NAME,int SIZE,int ROUNDED);
void function_profiler (FILE*asm_file,int labelno);
void initialize_trampoline (void);
void spim_epilogue (void);
